### ISSUE TITLE
cache.php line 57 will always error

### ISSUE THREAD

**Issue by quinten1333** [wvanbreukelen/ZermeloRoosterPHP#19] opened 2016-11-15 12:05 UTC
your function getToken() wil allways error if there is no code for the user stored. and since you call this function in grabaccescode($username,$password,$savetoken = true) you can't login without commenting it

**Comment by wvanbreukelen** [comment] 2016-11-16 13:16
Can you provide me a stacktrace with the thrown errors? Now, it is diificult for me to understand what is going on.

**Comment by quinten1333** [comment] 2016-11-16 13:59
the situation:
my cache.json contains only `{}` so this is the first login.

if the function doesn't return an code it throws the exeption so this made me unable to get the acces token without commenting line 57.

`[Wed Nov 16 14:52:44.349626 2016] [:error] [pid 12105] [client ::1:52368] PHP Fatal error:  Uncaught exception 'Exception' with message 'Cannot get token for 415980' in /home/quinten/Desktop/zermeloroosterphp/Cache.php:57\nStack trace:\n#0 /home/quinten/Desktop/zermeloroosterphp/Zermelo.php(215): ZermeloAPI\\Cache->getToken('415980')\n#1 /home/quinten/Desktop/zermeloroosterphp/test.php(19): ZermeloAPI->grabAccessToken('415980', 'hack-me')\n#2 {main}\n  thrown in /home/quinten/Desktop/zermeloroosterphp/Cache.php on line 57`

im on the main branch but il switch to the version you suggested in the other issue

**Comment by wvanbreukelen** [comment] 2016-11-16 14:48
Did you ran the method ```php $zermelo->grabAccessToken('username', code); ``` before $grid = $zermelo->getStudentGrid('user');
Please run only ```php $zermelo->grabAccessToken('username', code);```` and see if the cache.json (which has to be in the same location as Cache.php) has been updated.

**Comment by wvanbreukelen** [comment] 2016-11-22 19:13
@quinten1333 Did you manage to get it working?

**Comment by tomudding** [comment] 2016-11-23 09:04
I am not able to open a new PR at the moment but I suggest you try to catch the exception like this (Zermelo.php):

```
try {
    if ($token = $this->getCache()->getToken($username)) {
        return $token;
    }
} catch(Exception $e) {
    echo "An error occurred while fetching token from cache, see stack trace.\n";
    echo $e;
}
```

**Comment by quinten1333** [comment] 2016-11-23 10:03
@wvanbreukelen sorry for my late reaction, i need to check this more. if i only do grabaccestoken() it stil bugs at line 57 a.k.a. it trows the exception.

**Comment by quinten1333** [comment] 2016-11-23 16:33
@tomudding that shoudn't crash the code indeed but, i think there should be an if statement if the code is saved in the first place. inside the function getToken().

**Comment by tomudding** [comment] 2016-11-23 16:54
@quinten1333 completely agree with that, my code was just an example for a solution if @wvanbreukelen does not want to remove the `throw new Exception("Cannot get token for " . $id);` code in `Cache.php`.

It is also possible can clean up your suggested code a little bit more, just make it
```
if (($token = $this->getCache()->getToken($username)) && ($token != 'none')) {
    return $token;
}
```

**Comment by wvanbreukelen** [comment] 2016-11-23 20:05
@quinten1333 @tomudding Some issues seems to be fixed now.  Please redownload version/branch 1.0.6, and run the following in a clean environment (delete your cache.json file)

```php
<?php

// Including the Zermelo API PHP using the build-in autoloader
require('custom_autoload.php');

register_zermelo_api();

// Create a new Zermelo instance
$zermelo = new ZermeloAPI('mlfbhc');

// Get a new access token using a username and code
try {
	$zermelo->grabAccessToken('USER_NUMBER', 'CODE_FROM_ZPORTAL');
} catch (Exception $e) {
	echo "Failed to receive token. Error: ";
	print($e);
}

and post the output here

print_r($zermelo->getCache()->getRaw());
```

**Comment by quinten1333** [comment] 2016-11-24 09:24
cache.json doesn't exist.

(after creating it)

`failed to get codeexception 'Exception' with message 'Cannot get token for 415980' in /home/quinten/Desktop/ZermeloRoosterPHP/Cache.php:57 Stack trace: #0 /home/quinten/Desktop/ZermeloRoosterPHP/Zermelo.php(215): ZermeloAPI\Cache->getToken('415980') #1 /home/quinten/Desktop/ZermeloRoosterPHP/github.php(18): ZermeloAPI->grabAccessToken('415980', 'password') #2 {main}`

**Comment by wvanbreukelen** [comment] 2016-11-24 10:20
@quinten1333 Mmm weird. The following output at the end ```{"tokens":{"415980":"pODhr5tifk816mov4mik9a6jq8"}}``` tells me that there is actually a token saved in the cache.json file.
Did you make sure it is not a file permission problem? That could be the case.

Also ```pODhr5tifk816mov4mik9a6jq8``` doesn't seem te be a valid authentication code. Please request a new token using the grabAccessToken function()

After that:

If you run the code below, you should receive the latest grid
```php
<?php

// Including the Zermelo API PHP using the build-in autoloader
require('custom_autoload.php');

register_zermelo_api();

// Create a new Zermelo instance
$zermelo = new ZermeloAPI('mlfbhc');

// Dump cache contents
print_r($zermelo->getCache()->getRaw());

// Dump grid
print_r($zermelo->getStudentGrid('415980'));
```


The thrown exception is valid, because your given zportal app code ('sdfsdf') is incorrect. It has to be a (not sure) 9 digit number, without spaces.

**Comment by tomudding** [comment] 2016-11-24 14:04
@wvanbreukelen the token `pODhr5tifk816mov4mik9a6jq8 ` looks correct according to the Zermelo Developer pages. I think @quinten1333 changed the actual app code because it is session specific (changes when logging into Zermelo), so it could have been active a the moment.

I'll setup a test server (tomorrow) and test some new code (just testing my own code), I'll let you know if I find something that works better/fixes the issue.

**Comment by wvanbreukelen** [comment] 2016-11-24 14:18
@tomudding The token stays the same, evens when logged in into Zermelo (this was at the moment I developed this wrapper, not sure about this) It don't seem logical to change the token everytime a user is logging in to zportal.

What it don't understand completely is what the issue is at the moment. File creation of cache.json works at my end (Windows and Linux), with the latest commits I published yesterday (in branch 1.0.6) Token requests work aswell.
Could you specify the concrete issue you and Quinten are experiencing?

**Comment by tomudding** [comment] 2016-11-24 15:09
I do not have any problems (on macOS Server, Windows Server and Linux). I never really had the 'issue', I could only see why it would fail and that is what I tried to denote.

I think this can marked as fixed.

**Comment by wvanbreukelen** [comment] 2016-11-24 19:04
@tomudding Ah it is clear to me now. Thank you for your help!
By the way, I forgot to mention that the token is the auth-token, not the 'Koppel App'-token ;)

I will for a little longer before I close the issue, see if @quinten1333 does respond.

**Comment by quinten1333** [comment] 2016-11-24 20:56
@wvanbreukelen i know sdfsdf isn't correct, i fill my password for mlfbhc.zportal.nl, the 9 digit code doesn't work for me. also i changed the token a bit so jou cant hack me(wait, whats the problem if you can see my schedual xD).

**Comment by tomudding** [comment] 2016-11-24 21:18
@quinten1333 9 digit code? ZPortal gives a 12 digit code by default, I am right? Perhaps is that the problem.

**Comment by wvanbreukelen** [comment] 2016-11-24 23:18
It is indeed a 12 digit code. @quinten1333 Could you make a screenshot of your file structure?

**Comment by quinten1333** [comment] 2016-11-25 10:02
@tomudding @wvanbreukelen o sorry i mean 12 digit code. 
here is the output of `ls -l`
`-rw-rw-r-- 1 quinten quinten  1463 Nov 24 10:36 CHANGELOG.md
-rw-rw-r-- 1 quinten quinten  2431 Nov 24 10:36 Cache.php
-rw-rw-r-- 1 quinten quinten  3268 Nov 24 10:36 README.md
-rw-rw-r-- 1 quinten quinten 12226 Nov 24 10:36 Zermelo.php
-rwxrwxrwx 1 quinten quinten    50 Nov 24 10:29 cache.json
-rw-rw-r-- 1 quinten quinten   263 Nov 24 08:23 composer.json
-rw-rw-r-- 1 quinten quinten   316 Nov 24 08:23 custom_autoload.php
-rw-rw-r-- 1 quinten quinten   381 Nov 24 08:23 example.php
-rw-rw-r-- 1 quinten quinten   534 Nov 24 10:28 github.php new
-rw-rw-r-- 1 quinten quinten  1652 Nov 21 12:18 test.php    new
-rw-rw-r-- 1 quinten quinten    52 Nov 20 13:41 variables.php new
`

**Comment by quinten1333** [comment] 2016-11-25 10:23
i've made an pull request which fixed the bug for me.

**Comment by wvanbreukelen** [comment] 2016-11-25 11:02
Thanks for your PR. I am going to implement this later. Although, it is a better practice to use null, instead of a string value 'none'. Also, there is some room for optimalisation with the rest of the code.

**Closed by wvanbreukelen** 2016-11-25 11:02 UTC
Labels: help wanted
